{application,hw_conbee_app,
             [{description,"An OTP application"},
              {vsn,"0.1.0"},
              {registered,[]},
              {mod,{hw_conbee_app_app,[]}},
              {applications,[kernel,stdlib]},
              {env,[]},
              {modules,[hw_conbee_app_app,hw_conbee_app_server,
                        hw_conbee_app_sup]},
              {licenses,["Apache-2.0"]},
              {links,[]}]}.
